# Generated by Django 3.2.12 on 2022-03-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcity', models.CharField(choices=[('Addis Ketema', 'AK'), ('Bole', 'Bole'), ('Nifas Silk', 'NS'), ('Kolfe', 'Kolfe')], default='B', max_length=20)),
                ('woreda', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=30)),
                ('role', models.CharField(default='', max_length=20)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('device_id', models.CharField(default='', max_length=20)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cleanaddisAPI.address')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleanaddisAPI.address')),
            ],
        ),
    ]
