# Generated by Django 3.2.12 on 2022-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
