# Generated by Django 3.2.12 on 2022-05-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0002_auto_20220520_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSeen', models.BooleanField(default=False)),
                ('notificationtype', models.CharField(max_length=10)),
                ('user', models.IntegerField()),
                ('point_to', models.IntegerField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=14, unique=True),
        ),
        migrations.AlterField(
            model_name='publicplace',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=14, unique=True),
        ),
    ]
