# Generated by Django 3.2.12 on 2022-04-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0003_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_name', models.CharField(max_length=20)),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('Metal', 'Metal'), ('Aluminium', 'Almuinium'), ('Paper', 'Paper'), ('Old Gadgets', 'Old Gadgets'), ('Glass', 'Glass')], max_length=20)),
                ('for_waste', models.IntegerField(choices=[(1, 'Sell'), (2, 'Donate')])),
                ('price_per_unit', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('metric', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('loaction', models.CharField(max_length=30, null=True)),
                ('sold', models.BooleanField(null=True)),
                ('bought', models.BooleanField(null=True)),
                ('donated', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cleanaddisAPI.user')),
            ],
        ),
    ]
