# Generated by Django 2.2.12 on 2022-04-16 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0007_auto_20220416_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='loaction',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reportedBy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cleanaddisAPI.User'),
            preserve_default=False,
        ),
    ]
