# Generated by Django 2.2.12 on 2022-04-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0008_auto_20220416_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeID', models.CharField(default='', max_length=20, null=True)),
                ('placeName', models.CharField(default='', max_length=20, null=True)),
                ('placeType', models.CharField(choices=[('Toilet', 'Toilet'), ('Park', 'Park')], max_length=20)),
                ('rating', models.CharField(default='', max_length=5, null=True)),
                ('loaction', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminarID', models.CharField(default='', max_length=20, null=True)),
                ('seminarTitle', models.CharField(default='', max_length=20, null=True)),
                ('seminarDescription', models.CharField(default='', max_length=20, null=True)),
                ('seminarType', models.CharField(choices=[('Meeting', 'Meeting'), ('Plantation', 'Plantation'), ('Cleaning', 'Cleaning')], max_length=20)),
                ('loaction', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workID', models.CharField(default='', max_length=20, null=True)),
                ('date', models.CharField(default='', max_length=20, null=True)),
                ('hour', models.CharField(default='', max_length=20, null=True)),
            ],
        ),
    ]
