# Generated by Django 2.2.12 on 2022-04-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0009_publicplace_seminar_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='hour',
            field=models.DateField(default='', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationID', models.IntegerField(default='', max_length=20, null=True)),
                ('notificationTitle', models.CharField(default='', max_length=20, null=True)),
                ('notificationDescription', models.CharField(default='', max_length=20, null=True)),
                ('formDate', models.DateField(default='', max_length=20, null=True)),
                ('toDate', models.DateField(default='', max_length=20, null=True)),
                ('published', models.DateField(default='', max_length=20, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cleanaddisAPI.User')),
            ],
        ),
    ]
