# Generated by Django 3.2.12 on 2022-06-19 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0010_auto_20220618_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recycle_item',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Qorale', 'Qorale'), ('Garbage Collector', 'Garbage Collector'), ('City Admin', 'City Admin'), ('Resident', 'Resident'), ('Recycler', 'Recycler'), ('Charity', 'Charity')], default='Resident', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='waste',
            name='buyer',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waste',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
