# Generated by Django 3.2.12 on 2022-05-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanaddisAPI', '0008_auto_20220422_1346'),
        ('cleanaddisAPI', '0010_auto_20220417_0001'),
    ]

    operations = [
    ]
